name: remote-toy-website-rg
concurrency: toy-company

on:
  [workflow_dispatch]
  # schedule:
  #   - cron: '0 0 * * *'

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCEGROUP_NAME: ToyWebsite

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Run Azure PowerShell inline script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Remove-AzResourceGroup -Name  ${{ env.AZURE_RESOURCEGROUP_NAME }} -Force
          azPSVersion: "latest"
